### ISSUE TITLE
SSGI with Three Js Lights

### ISSUE THREAD

**Issue by gnansai** [0beqz/realism-effects#9]
Hi @0beqz ,
Thanks for making the realism-effects. SSGI works great with HDRI images.

Does it support three js Lights? I tested it with three js Sunlamp, SSGI does not seems to work.

**Comment by 0beqz** [comment]
Hey,

thanks and it does, at least for the directional light I've tested with. So you can also make SSGI use the lighting from the basic three.js scene:
1. Add a directional light to your scene
2. If you are using ambient lighting, remove it
3. Make sure to use a RenderPass so that SSGI can use the lighting from the rendered three.js scene

Your basic three.js scene will be all black except for the areas illuminated by your light. SSGI will then use that lighting information for direct lighting.

**Comment by gnansai** [comment]
Thank you for the information, I will test it.
